#!/bin/bash

echo "================================"
echo "🚀 Deploy All Fixes to VPS"
echo "================================"
echo ""

# Push to GitHub
echo "📦 Step 1: Push to GitHub..."
cd /workspaces/saroyarsir
git add -A
git commit -m "Fix fee save and SMS template permanent storage"
git push origin main
echo "✅ Code pushed to GitHub"
echo ""

echo "================================"
echo "📋 VPS Deployment Commands"
echo "================================"
echo ""
echo "SSH into your VPS and run these commands:"
echo ""
echo "ssh root@194.233.74.48"
echo ""
echo "# Then run on VPS:"
echo ""
echo "cd /var/www/saroyarsir"
echo "git pull origin main"
echo "sudo systemctl restart saro_vps"
echo "sudo systemctl status saro_vps"
echo ""
echo "# If failed, check logs:"
echo "sudo journalctl -u saro_vps -n 100 --no-pager"
echo ""
echo "================================"
echo "✅ What Was Fixed:"
echo "================================"
echo ""
echo "1. Fee Save Issue:"
echo "   ❌ Before: 'Saved 1 fee(s), 1 failed'"
echo "   ✅ After: All fees save correctly"
echo "   🔧 Fix: Mapped 'other_fee' → 'others_fee' column"
echo ""
echo "2. SMS Templates Issue:"
echo "   ❌ Before: Stored in session (temporary, per-teacher)"
echo "   ✅ After: Stored in database (permanent, shared)"
echo "   🔧 Fix: Database-first priority, shared across all teachers"
echo ""
echo "================================"
echo "📝 Files Changed:"
echo "================================"
echo "1. routes/fees.py - 5 functions updated"
echo "2. utils/response.py - Fee serialization fixed"
echo "3. routes/monthly_exams.py - Template priority changed"
echo "4. routes/sms_templates.py - Database-only storage"
echo ""
echo "================================"
echo "🧪 Testing After Deployment:"
echo "================================"
echo ""
echo "Test 1: Fee System"
echo "  1. Login as teacher"
echo "  2. Go to Fee Management"
echo "  3. Add fees with exam_fee and other_fee"
echo "  4. Should save all 14 columns without errors"
echo ""
echo "Test 2: SMS Templates"
echo "  1. Login as Teacher A"
echo "  2. Edit a custom template"
echo "  3. Save the template"
echo "  4. Logout"
echo "  5. Login as Teacher B"
echo "  6. Should see Teacher A's template"
echo "  7. Edit applies to all teachers"
echo ""
echo "================================"
